rules_folder: rules

run_every:
  seconds: 10

buffer_time:
  minutes: 15

es_host: 10.1.20.9
es_port: 9200

es_username: "elastic"
es_password: "EJXBX6X9c4BwKbfhtuK2"

writeback_index: elastalert_status1

alert_time_limit:
  days: 2
